RunPropagator: RunPropagator.cc Emitter.cc Propagator.cc Reflector.cc Ice.cc RFRay.cc RFRayTracker.cc Collector.cc Reflections.cc Refractions.cc
	g++ -std=c++11 -o RunPropagator RunPropagator.cc Emitter.cc Propagator.cc Reflector.cc Ice.cc RFRay.cc RFRayTracker.cc Collector.cc Reflections.cc Refractions.cc -I.

clean:
	rm RunPropagator
